### ISSUE TITLE
toBeInstanceOf matcher

### ISSUE THREAD

**Issue by blainekasten** [blainekasten/jasmine-enzyme#26]
Name up for discussion.
Idea is that if I want to check that a wrapper is a specific component, I could assert easily.

```js
expect(wrapper).toBeInstanceOf(MyCustomComp);
```

Is the name correct?

**Comment by blainekasten** [comment]
I think the implementation would be something like:

```js
toBeInstanceOf(expected, actual) {
  return {
    pass: expected.type() === actual,
  }
}

**Comment by tronroy** [comment]
Would the name be better if it were something like `toBeType` or `toBeOfType`? It might mentally map better to the enzyme method `type` that would be used in the assertion.

**Comment by blainekasten** [comment]
Also sort of concerned that it would infer `typeof` asserting. Though to be fair, `toBeInstanceOf` feels like an alias to `expect(foo instanceOf bar).toBeTruthy()`

Internally in React, code that refers to instantiated React Components is typically used with a variable of `var _inst`. So that makes me like instance again. 

maybe `toBeInstOfComponent(Component)`?

**Comment by tronroy** [comment]
I actually don't think `toBeInstanceOf` is a bad name. I guess what is bothering me at first is that the implementation of `toBeInstanceOf` would be the same as `toHaveTagName` since both would be testing the nodes by calling `.type()` on them. That's why I suggested a broader name like `toBeType` (which I agree is not ideal).

Maybe `toBeInstanceOf` would be better for something like this:

```
toBeInstanceOf(expectedInstance) {
  return {
    pass: wrapper.instance() === expectedInstance,
  }
}
```
The only problem is `.instance()` only works if called on a "wrapper instance that is also the root instance," meaning you couldn't use it to test components that lived further down in the tree.

Hope this makes sense.

**Comment by blainekasten** [comment]
> The only problem is .instance() only works if called on a "wrapper instance that is also the root instance," meaning you couldn't use it to test components that lived further down in the tree.

True. That wouldn't add any benefit really.


I guess at the end of the day this matcher idea is the same as using `toHaveTagName` except you are matching on the definition instead of the tag name.

```js
toBeInstanceOf(MyComp);
toHaveTagName('MyComp');
```

This also can be achieved with the `toMatchSelector` matcher since enzyme supports declaration matching anyhow.

```js
toMatchSelector(MyComp);
```

With that in mind. I think this is not actually a worthwhile assertion. I'm going to close this out. Feel free to comment if you can think of a good use case for this actually.
